### ISSUE TITLE
All kotlinx synthetic view accessors should be referenced in the inflated layout

### ISSUE THREAD

**Issue by Serchinastico** [Serchinastico/Lin#30]
It's a common mistake to load a different view from a different layout with the same id and spend a lot of time trying to figure out what the error is.

There shouldn't be any reference to any view out of the activity/fragment layout.

**Comment by Tylos** [comment]
![](https://media.giphy.com/media/5bgTdDtgmnrBagJzIU/giphy.gif)

**Comment by Serchinastico** [comment]
Thank you @Tylos for such a great rule idea 💃
